itinerary/urls.py
from django.conf.urls import url

from itinerary.views import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

itinerary_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from itinerary.views import views
from rest_framework.routers import DefaultRouter

#Use this for the api
router = DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'trips', views.TripViewSet)
router.register(r'days', views.DayViewSet)
router.register(r'items', views.ItemViewSet)

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^create/', views.createTrip, name='create'),
	url(r'^allTrips/', views.showAllTrips, name='allTrips'),
	url(r'^trip/(?P<tripID>\d+)', views.showTrip, name='showTrip'),
	url(r'^login/', views.login, name='login'),
	url(r'^myTrips/', views.viewMyTrips, name='myTrips'),
	url(r'^getFriends/', views.getFriends, name='getFriends'),
	url(r'^shareWithFriends/', views.shareWithFriends, name='shareWithFriends'),
	url(r'^pastTrips/', views.viewPastTrips, name='pastTrips'),
	url(r'^updateItemPositions', views.updateItemPositions, name='updateItemPositions'),
	url(r'^yelpTest/', views.yelpTest, name='yelpTest'),
	url(r'^getFoursquareResults?', views.getFoursquareResults, name='getFoursquareResults'),
	url(r'^getFoursquareVenue', views.getFoursquareVenue, name='getFoursquareVenue'),
	url(r'^updateStartLocations', views.updateStartLocations, name='updateStartLocations'),
	url(r'^removeFromInterested', views.removeFromInterested, name='removeFromInterested'),
	url(r'^moveToInterested/(?P<itemID>\d+)', views.moveToInterested, name='moveToInterested'),
    url(r'^admin/', admin.site.urls),
	url(r'^api/', include(router.urls)),
]

itinerary/models.py
from django.db import models

class User(models.Model):
    fb_id = models.BigIntegerField(primary_key=True)
    email = models.CharField(max_length=100, unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)

class Trip(models.Model):
    location = models.CharField(max_length=100)
    longitude = models.DecimalField(decimal_places=15, max_digits=18, null=True)
    latitude = models.DecimalField(decimal_places=15, max_digits=18, null=True)
    trip_name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000, null=True)
    start_date = models.DateField()
    end_date = models.DateField()
    create_date = models.DateTimeField(auto_now=True)
    can_edit = models.BooleanField(default=False)
    popularity = models.PositiveIntegerField(default=0)
    creator = models.ForeignKey(User)
    shared_users = models.ManyToManyField(User, related_name='shared_users')

    EVERYBODY = 'E'
    FRIENDS = 'F'
    SHARED = 'S'
    PUBLIC_LEVEL_CHOICES = (
        (EVERYBODY, 'Everybody'),
        (FRIENDS, 'Only Friends'),
        (SHARED, 'Only Friends That I Choose')
    )

    public_level = models.CharField(max_length=1, choices=PUBLIC_LEVEL_CHOICES, default=EVERYBODY)

    def __str__(self):
        return self.trip_name

class Day(models.Model):
    date = models.DateField()
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    day_start_address = models.CharField(max_length=100, null=True)
    day_start_longitude = models.DecimalField(decimal_places=15, max_digits=18, null=True)
    day_start_latitude = models.DecimalField(decimal_places=15, max_digits=18, null=True)

    def __str__(self):
        return str(self.date)

class Item(models.Model):
    fsq_id = models.CharField(max_length=50, null=True)
    item_name = models.CharField(max_length=100)
    item_position = models.PositiveIntegerField(null=True)
    item_description = models.CharField(max_length=1000, null=True)
    start_time = models.DateTimeField(null=True)
    end_time = models.DateTimeField(null=True)
    item_longitude = models.DecimalField(decimal_places=15, max_digits=18, null=True)
    item_latitude = models.DecimalField(decimal_places=15, max_digits=18, null=True)
    day = models.ForeignKey(Day, on_delete=models.CASCADE, null=True)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE, null=True)
    user_added = models.ForeignKey(User)

    def __str__(self):
        return self.item_name

itinerary/views/forms.py
from django import forms

class CreateTripForm(forms.Form):
    location = forms.CharField(label="Location", max_length=100)
    longitude = forms.DecimalField(widget=forms.HiddenInput())
    latitude = forms.DecimalField(widget=forms.HiddenInput())
    trip_name = forms.CharField(label="Trip Name", max_length=100, required=False)
    description = forms.CharField(label="Trip Description", widget=forms.Textarea, max_length=1000, required=False)
    start_date = forms.DateField(label="Start Date", widget=forms.DateInput)
    end_date = forms.DateField(label="End Date", widget=forms.DateInput)

    EVERYBODY = 'E'
    FRIENDS = 'F'
    SHARED = 'S'
    PUBLIC_LEVEL_CHOICES = (
        (EVERYBODY, 'Everybody'),
        (FRIENDS, 'Only Friends'),
        (SHARED, 'Only Friends That I Choose')
    )

    public = forms.CharField(label="Public Level", max_length=1, widget=forms.Select(choices=PUBLIC_LEVEL_CHOICES))

itinerary/views/serializers.py
from rest_framework import serializers
from itinerary.models import Trip, Day, Item, User

class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('fb_id', 'email', 'first_name', 'last_name')

class TripSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Trip
        fields = ('location', 'longitude', 'latitude', 'trip_name', 'description', 'start_date', 'end_date', 'create_date', 'public', 'can_edit', 'popularity')

class DaySerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Day
        fields = ('date', 'trip')

class ItemSerializer(serializers.HyperlinkedModelSerializer):
    def create(self, validated_data):
        trip = validated_data['trip']
        session = self.context.get('request').session
        permissions = session['trip_permission']
        if trip.id == int(session['current_trip']) and (permissions == "Creator" or permissions == "Can Edit"):
            try:
                day = validated_data['day']
                print(day)
                if day.trip.id == trip.id:
                    #Find the highest item position in a day and put the new item above that
                    highest_position = Item.objects.filter(day_id=day.id).order_by('-item_position')[:1]
                    #If the day is empty, new item is in position 1
                    next_position = 1
                    if highest_position:
                        next_position = highest_position[0].item_position + 1
                    validated_data['item_position'] = next_position
            except KeyError:
                pass
            user_added = User.objects.get(fb_id=session['fb_id'])
            validated_data['user_added'] = user_added
            #Once new item has a position, create the object in database
            item = Item.objects.create(**validated_data)
            return item

    class Meta:
        model = Item
        fields = ('id', 'fsq_id', 'item_name', 'item_description', 'start_time', 'end_time', 'item_longitude', 'item_latitude', 'day', 'trip')

itinerary/views/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.core.cache import cache
from itinerary.models import Trip, Day, Item, User
from itinerary.views.forms import CreateTripForm
from itinerary.views.api_ids import Ids
from datetime import timedelta, date
from rest_framework import viewsets
from django.views.decorators.csrf import ensure_csrf_cookie
from itinerary.views.serializers import TripSerializer, DaySerializer, ItemSerializer, UserSerializer
import requests
import facebook
import json
import decimal

def index(request):
    return render(request, 'home.html')

def createTrip(request):
    if request.method == 'POST':
        #Get information from form and validate
        form = CreateTripForm(request.POST)
        if form.is_valid():
            creator = User.objects.get(fb_id=request.session['fb_id'])
            location = form.cleaned_data['location']
            longitude = form.cleaned_data['longitude']
            latitude = form.cleaned_data['latitude']
            trip_name = form.cleaned_data['trip_name']
            description = form.cleaned_data['description']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            public_level = form.cleaned_data['public']

            #If no trip name is given, use the lcoation as the name
            if not trip_name:
                trip_name = location

            #Create the trip
            trip = Trip(creator=creator, location=location, longitude=longitude, latitude=latitude, trip_name=trip_name, description=description, start_date=start_date, end_date=end_date, public_level=public_level)
            trip.save()

            #For each day of the trip, create a day object
            trip_duration = (end_date - start_date).days
            increment = timedelta(days=1)
            current_day = start_date
            day = Day(date=current_day, trip=trip)
            day.save()

            for num in range(0, trip_duration):
                current_day = current_day + increment
                day = Day(date=current_day, trip=trip)
                day.save()

            #Once trip is created, show it
            return redirect('showTrip', tripID=trip.id)

    else:
        #Show the trip creation form
        form = CreateTripForm()
        return render(request, 'createTrip.html', {'form': form})

def showAllTrips(request):
    #For development purposes only - Should not be in final product
    trips = Trip.objects.all()
    return render(request, 'allTrips.html', {'trips': trips})

@ensure_csrf_cookie
def showTrip(request, tripID):
    #TODO: Only allow those who have permission edit to edit
    error = None
    try:
        trip = Trip.objects.get(id=tripID)
        #Check to see if user can access trip
        response = canViewTrip(request, trip)
        if response:
            request.session['current_trip'] = tripID
            request.session['trip_permission'] = response
            #Fetch day and item information for the trip
            days = Day.objects.filter(trip_id=tripID).order_by('date')
            for day in days:
                items = Item.objects.filter(day_id=day.id).order_by('item_position')
                day.items = items
            interestedItems = Item.objects.filter(trip_id=trip.id, day_id=None)
            return render(request, 'showTrip.html', {'trip': trip, 'days': days, 'interested': interestedItems, 'permissions': response})
        else:
            #If user can't access trip
            return render(request, 'showTrip.html', {'error': 'You do not have access to this trip'})
    except Trip.DoesNotExist:
        #If trip does not exist
        error = 'This trip does not exist'
        return render(request, 'showTrip.html', {'error': error})

def canViewTrip(request, trip):
    if 'fb_id' in request.session:
        fb_id = int(request.session['fb_id'])
        #User is the creator
        if fb_id == trip.creator.fb_id:
            return 'Creator'

        #Trip has been shared with the User
        shared = trip.shared_users.only('fb_id')
        for user in shared:
            if fb_id == user.fb_id:
                return 'Can Edit'

        #User is friends with the trip creator
        if trip.public_level == 'F' and 'access_token' in request.session:
            graph = facebook.GraphAPI(access_token=request.session['access_token'], version='2.7')
            friends = graph.get_connections(id=request.session['fb_id'], connection_name='friends')
            for user in friends['data']:
                if int(user['id']) == trip.creator.fb_id:
                    return 'Can View'

    #The trip is public
    if trip.public_level == 'E':
        return 'Can View'

    #User does not have access to the trip
    return False

def viewMyTrips(request):
    #Get user, then search for trips created by that user
    if 'fb_id' in request.session:
        fb_id = int(request.session['fb_id'])
        user = User.objects.get(fb_id=fb_id)
        #Current trips are in progress, with a start date before today and end date after today
        current_trips = Trip.objects.filter(creator=user).filter(start_date__lte=date.today()).filter(end_date__gte=date.today()).only('id', 'trip_name', 'start_date', 'end_date').order_by('start_date')
        #Future trips have start date after today
        future_trips = Trip.objects.filter(creator=user).filter(start_date__gte=date.today()).only('id', 'trip_name', 'start_date', 'end_date').order_by('start_date')
        return render(request, 'myTrips.html', {'current_trips': current_trips, 'future_trips': future_trips})
    return render(request, 'error.html')

def viewPastTrips(request):
    #Only load in past trips upon request
    if 'fb_id' in request.session:
        fb_id = int(request.session['fb_id'])
        user = User.objects.get(fb_id=fb_id)
        #Get trips with an end date that is after today
        trips = Trip.objects.filter(creator=user).filter(end_date__lt=date.today()).order_by('-end_date')
        if trips.count() != 0:
            #Convert queryset into a serializable object
            response = {}
            response['data'] = []
            for trip in trips:
                data = {'id': trip.id, 'trip_name': trip.trip_name, 'start_date': trip.start_date, 'end_date': trip.end_date}
                response['data'].append(data)
            return JsonResponse({'trips': response})
        else:
            #If there are no past trips, send response
            return JsonResponse({'message': 'You do not have any past trips'})

def getFriends(request):
    #Need access token to get friends - Make sure it isn't expired
    if 'fb_id' in request.session and 'access_token' in request.session:
        fb_id = int(request.session['fb_id'])
        trip = Trip.objects.get(id=request.session['current_trip'])
        #Check again to make sure user is creator
        if fb_id == trip.creator.fb_id:
            graph = facebook.GraphAPI(access_token=request.session['access_token'], version='2.7')
            #Get friends using Graph API
            friends = graph.get_connections(id=fb_id, connection_name='friends')
            #Create json object with arrays of friends that have and have not been given access to edit trip
            friends_json = {}
            friends_json['shared'] = []
            friends_json['unshared'] = []
            #Get shared users for trip
            shared = trip.shared_users.only('fb_id')
            #Add friend id to the correct category
            for friend in friends['data']:
                unshared = True
                for user in shared:
                    if int(friend['id']) == user.fb_id:
                        friends_json['shared'].append(friend)
                        unshared = False
                        break
                if unshared:
                    friends_json['unshared'].append(friend)
            return JsonResponse(friends_json)

def shareWithFriends(request):
    if 'fb_id' in request.session:
        fb_id = int(request.session['fb_id'])
        trip = Trip.objects.get(id=request.session['current_trip'])
        #Check again to make sure user is creator
        if fb_id == trip.creator.fb_id:
            id_list = request.POST.getlist('id_list[]', '0')
            #Clear all the shared users - In case user wants to remove permissions for someone
            trip.shared_users.clear()
            if id_list != '0':
                for id in id_list:
                    #Add users to shared
                    user = User.objects.get(fb_id=int(id))
                    trip.shared_users.add(user)
            return HttpResponse("Friends added to trip")

#Update all the positions of items in a trip
def updateItemPositions(request):
    #Get items from the post request as an array
    items = request.POST.getlist('items[]', '0')
    #Covert each item in the array into a json object
    for index in range(len(items)):
        items[index] = json.loads(items[index])
    #If items are part of this trip, update their day and positions
    if validateItems(request, items):
        for item in items:
            item_object = Item.objects.get(id=item['item_id'])
            if item['day_id'] == None:
                item_object.day = None
                item_object.item_position = None
            else:
                item_object.day = Day.objects.get(id=item['day_id'])
                item_object.item_position = item['position']
            item_object.save()
        return HttpResponse("Items updated")
    else:
        return HttpResponse("Something went wrong")

#Make sure all items are from the same trip
def validateItems(request, items):
    #The current trip should be the one that user has in their session
    current_trip = Trip.objects.get(id=request.session['current_trip'])
    #Loop through items and check each of their trip ids
    for item in items:

itinerary/templates/allTrips.html
<!DOCTYPE html>
<html>
<head>
    <title>Itinerary Website</title>
    <link rel="stylesheet" href="/static/style/jquery-ui.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="/static/scripts/jquery-ui.min.js"></script>
    <script src="/static/scripts/script.js"></script>
</head>

<body>
    {% if trips %}
        {% for trip in trips %}
            <p><a href='/trip/{{trip.id}}'>{{trip.trip_name}}</a></p>
        {% endfor %}
    {% else %}
        <p>There are no trips created yet</p>
    {% endif %}
</body>
</html>

itinerary/templates/createTrip.html
<!DOCTYPE html>
<html>
<head>
    <title>Itinerary Website</title>
    <link rel="stylesheet" href="/static/style/jquery-ui.min.css">
    <link rel="stylesheet" href="/static/style/style.css">
    <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.1.0/mapbox-gl-geocoder.css' type='text/css' />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="/static/scripts/jquery-ui.min.js"></script>
    <script src="/static/scripts/script.js"></script>
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.38.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.38.0/mapbox-gl.css' rel='stylesheet' />
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
</head>

<body>

    <div id="map" style='width: 1200px; height: 900px;'> </div>

    <nav id='listing-group' class='listing-group'>
        <input type='checkbox' id='scrollZoom' checked='checked'>
        <label for='scrollZoom'>Scroll zoom</label>
        <input type='checkbox' id='boxZoom' checked='checked'>
        <label for='boxZoom'>Box zoom</label>
        <input type='checkbox' id='dragRotate' checked='checked'>
        <label for='dragRotate'>Drag rotate</label>
        <input type='checkbox' id='dragPan' checked='checked'>
        <label for='dragPan'>Drag pan</label>
        <input type='checkbox' id='keyboard' checked='checked'>
        <label for='keyboard'>Keyboard</label>
        <input type='checkbox' id='doubleClickZoom' checked='checked'>
        <label for='doubleClickZoom'>Double click zoom</label>
        <input type='checkbox' id='touchZoomRotate' checked='checked'>
        <label for='touchZoomRotate'>Touch zoom rotate</label>
    </nav>

    <form action="/create/" method="POST" autocomplete="off">
        {% csrf_token %}
        <div>
            {{ form.location.errors }}
            <label for="{{ form.location.id_for_label }}">Location: </label>
            <div class="inline_block">
                {{ form.location }}
                <div id="autocomplete_area"></div>
            </div>
        </div>
        {{ form.longitude }}
        {{ form.latitude }}
        <div>
            {{ form.trip_name.errors }}
            <label for="{{ form.trip_name.id_for_label }}">Trip Name: </label>
            {{ form.trip_name }}
        </div>
        <div>
            {{ form.description.errors }}
            <label for="{{ form.description.id_for_label }}">Description: </label>
            {{ form.description }}
        </div>
        <div>
            {{ form.start_date.errors }}
            <label for="{{ form.start_date.id_for_label }}">Start Date: </label>
            {{ form.start_date }}
        </div>
        <div>
            {{ form.end_date.errors }}
            <label for="{{ form.end_date.id_for_label }}">End Date: </label>
            {{ form.end_date }}
        </div>
        <div>
            {{ form.public.errors }}
            <label for="{{ form.public.id_for_label }}">Who can see this trip: </label>
            {{ form.public }}
        </div>
        <input type="submit" value="Create" id="create_submit"/>
    </form>

    <script>
        //Add the JQuery calenders to the two input fields
        $('#id_start_date').datepicker({dateFormat: "yy-mm-dd"});
        $('#id_end_date').datepicker({dateFormat: "yy-mm-dd"});
    </script>

    <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoiaGVpcG8iLCJhIjoiY2o0NGt5ZjUwMDBucjJxbXFkY3NocDB6NiJ9.hpEpBTqgwgHHW-gSA6ZNzg';
        var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v10',
            center: [-71.0571, 42.3601], // starting position
            zoom: 9
        });

        map.addControl(new mapboxgl.NavigationControl());
        map.addControl(new mapboxgl.GeolocateControl());

        var layers = document.getElementById('listing-group');

        $("#create_submit").prop('disabled', true);
        var input_box = $("#id_location");

        input_box.keyup(function(event) {
            var query = input_box.val();
            if (query != old_query) {
                $("#id_longitude").val("");
                $("#id_latitude").val("");
                $("#create_submit").prop('disabled', true);
                old_query = query;

                if (query) {
                    searchAutocomplete(query, "place,address", "updateCoordinates");
                }
            }
        }).keydown(navigateAutocomplete)
        .focus(showAutocomplete);

        window.onclick = function(event) {
            if (event.target != document.getElementById("id_location") && event.target != document.getElementById("autocomplete_area")) {
                $("#autocomplete_area").hide();
            }
        }

        function updateCoordinates(index) {
            goToLocation(index, map);

            $("#id_longitude").val(autocomplete_options[index].center[0]);
            $("#id_latitude").val(autocomplete_options[index].center[1]);
            $("#create_submit").prop('disabled', false);
        }

        document.getElementById('listing-group').addEventListener('change', function(e) {
            var handler = e.target.id;
                if (e.target.checked) {
                        map[handler].enable();
                } else {
                        map[handler].disable();
                }
        });
    </script>
</body>
</html>

itinerary/templates/error.html
<!DOCTYPE html>
<html>
<head>
    <title>Itinerary Website</title>
    {% load static %}
    <link rel="stylesheet" href="/static/style/jquery-ui.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="/static/scripts/jquery-ui.min.js"></script>
    <script src="/static/scripts/script.js"></script>
</head>
<body>
    <h4>Something went wrong. <a href="/">Go back Home</a></h4>
</body>
</html>

itinerary/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Itinerary Website</title>
    {% load static %}
    <link rel="stylesheet" href="/static/style/jquery-ui.min.css">
    <link rel="stylesheet" href="/static/style/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="/static/scripts/jquery-ui.min.js"></script>
    <script src="/static/scripts/script.js"></script>
</head>

<body>
    <div id="site_title">
        <img src="/static/images/globe.gif" height="100" width="100">
        <h2>PlanIt</h2>
    </div>
    <div id="topbar">
        <div id="fb-root"></div>
        <script src="/static/scripts/fb_login.js"></script>
        <span id="user_info">
            <a href='/myTrips'><span id="full_name"></span>
            <span id="fb_picture"></span></a>
            <fb:login-button
                id="fb_login_button"
                scope="public_profile,email,user_friends"
                onlogin="checkLoginState();">
            </fb:login-button>
        </span>
    </div>
    <p><a href='/allTrips'>View All Trips</a></p>
    <p><a href='/myTrips'>View My Trips</a></p>
    <p><a href='/create'>Create a Trip</a></p>
</body>
</html>

itinerary/templates/myTrips.html
<!DOCTYPE html>
<html>
<head>
    <title>Itinerary Website</title>
    {% load static %}
    <link rel="stylesheet" href="/static/style/jquery-ui.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="/static/scripts/jquery-ui.min.js"></script>
    <script src="/static/scripts/script.js"></script>
</head>
<body>
    {% if current_trips %}
    <h3>Current Trips</h3>
    <div id="current_trips">
        {% for trip in current_trips %}
            <p><a href='/trip/{{trip.id}}'>{{trip.trip_name}}</a></p>
        {% endfor %}
    </div>
    {% endif %}
    <h3>Future Trips</h3>
    <div id="future_trips">
    {% if future_trips %}
        {% for trip in future_trips %}
            <p><a href='/trip/{{trip.id}}'>{{trip.trip_name}}</a></p>
        {% endfor %}
    {% else %}
        <p>You dont have any future trips planned. <a href="/create">Make one here!</a></p>
    {% endif %}
    </div>
    <h3 onclick="loadPastTrips()">Past Trips</h3>
    <div id="past_trips">
    </div>
</body>
</html>